import Task from "./Task";

export const MOCK_TASKS = [
    new Task({
        id: 1,
        title: "Design login page",
        description: "Create a responsive login page for the app.",
        assignedTo: "alice",
        dueDate: new Date("2025-08-15T10:00:00Z"),
        priority: "High",
        status: "In-progress",
        isArchived: false,
    }),
    new Task({
        id: 2,
        title: "Fix navigation bug",
        description: "Resolve the issue with navbar collapsing on mobile.",
        assignedTo: "bob",
        dueDate: new Date("2025-08-10T12:00:00Z"),
        priority: "Medium",
        status: "To Do",
        isArchived: false,
    }),
    new Task({
        id: 3,
        title: "Set up CI pipeline",
        description: "Integrate GitHub Actions for continuous integration.",
        assignedTo: "carol",
        dueDate: new Date("2025-08-20T08:30:00Z"),
        priority: "High",
        status: "In-progress",
        isArchived: false,
    }),
    new Task({
        id: 4,
        title: "Write unit tests",
        description: "Cover components with Jest unit tests.",
        assignedTo: "dave",
        dueDate: new Date("2025-08-18T15:00:00Z"),
        priority: "Low",
        status: "To Do",
        isArchived: false,
    }),
    new Task({
        id: 5,
        title: "Deploy to staging",
        description: "Push the latest build to the staging environment.",
        assignedTo: "eve",
        dueDate: new Date("2025-08-12T13:45:00Z"),
        priority: "Medium",
        status: "Done",
        isArchived: false,
    }),
    new Task({
        id: 6,
        title: "Archive old logs",
        description: "Move outdated log files to the archive bucket.",
        assignedTo: "frank",
        dueDate: new Date("2025-08-08T09:00:00Z"),
        priority: "Low",
        status: "Done",
        isArchived: true,
    }),
    new Task({
        id: 7,
        title: "This is a dummy task",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        assignedTo: "Anurag",
        dueDate: new Date("2025-08-08T09:00:00Z"),
        priority: "High",
        status: "Done",
        isArchived: true,
    }),
    new Task({
        id: 8,
        title: "Optimize database queries",
        description: "Refactor slow SQL queries to improve performance.",
        assignedTo: "alice",
        dueDate: new Date("2025-08-22T11:00:00Z"),
        priority: "High",
        status: "In-progress",
        isArchived: false,
    }),
    new Task({
        id: 9,
        title: "Update project documentation",
        description: "Ensure README and API docs are up to date.",
        assignedTo: "bob",
        dueDate: new Date("2025-08-25T16:30:00Z"),
        priority: "Medium",
        status: "To Do",
        isArchived: false,
    }),
    new Task({
        id: 10,
        title: "Refactor authentication module",
        description: "Simplify and secure the login flow using JWT.",
        assignedTo: "carol",
        dueDate: new Date("2025-08-28T14:00:00Z"),
        priority: "High",
        status: "In-progress",
        isArchived: false,
    }),
    new Task({
        id: 11,
        title: "Conduct accessibility audit",
        description: "Test the app with screen readers and color contrast tools.",
        assignedTo: "dave",
        dueDate: new Date("2025-08-30T09:00:00Z"),
        priority: "Low",
        status: "To Do",
        isArchived: false,
    }),
    new Task({
        id: 12,
        title: "Migrate to TypeScript",
        description: "Convert all JavaScript files to TypeScript.",
        assignedTo: "eve",
        dueDate: new Date("2025-09-02T10:15:00Z"),
        priority: "High",
        status: "In-progress",
        isArchived: false,
    }),
    new Task({
        id: 13,
        title: "Setup error tracking",
        description: "Integrate Sentry for frontend and backend error reporting.",
        assignedTo: "frank",
        dueDate: new Date("2025-09-04T12:00:00Z"),
        priority: "Medium",
        status: "To Do",
        isArchived: false,
    }),
    new Task({
        id: 14,
        title: "Prepare sprint demo",
        description: "Gather updates and prepare slides for the sprint review.",
        assignedTo: "alice",
        dueDate: new Date("2025-09-06T14:30:00Z"),
        priority: "Low",
        status: "In-progress",
        isArchived: false,
    }),
    new Task({
        id: 15,
        title: "Fix memory leak",
        description: "Investigate and patch memory leak in the Node.js server.",
        assignedTo: "bob",
        dueDate: new Date("2025-09-08T09:45:00Z"),
        priority: "High",
        status: "To Do",
        isArchived: false,
    }),
    new Task({
        id: 16,
        title: "Redesign dashboard UI",
        description: "Modernize the dashboard with a new grid layout.",
        assignedTo: "carol",
        dueDate: new Date("2025-09-10T11:20:00Z"),
        priority: "Medium",
        status: "In-progress",
        isArchived: false,
    }),
    new Task({
        id: 17,
        title: "Clean up staging database",
        description: "Remove outdated test records from staging DB.",
        assignedTo: "dave",
        dueDate: new Date("2025-09-12T15:30:00Z"),
        priority: "Low",
        status: "Done",
        isArchived: true,
    }),
    new Task({
        id: 18,
        title: "Create onboarding guide",
        description: "Write documentation for new developers joining the team.",
        assignedTo: "eve",
        dueDate: new Date("2025-09-15T10:00:00Z"),
        priority: "Medium",
        status: "To Do",
        isArchived: false,
    }),
    new Task({
        id: 19,
        title: "Configure CI caching",
        description: "Speed up builds by caching dependencies in CI.",
        assignedTo: "frank",
        dueDate: new Date("2025-09-18T12:45:00Z"),
        priority: "Low",
        status: "Done",
        isArchived: false,
    }),
    new Task({
        id: 20,
        title: "Implement dark mode",
        description: "Allow users to toggle between light and dark themes.",
        assignedTo: "alice",
        dueDate: new Date("2025-09-20T18:00:00Z"),
        priority: "High",
        status: "In-progress",
        isArchived: false,
    }),
    new Task({
        id: 21,
        title: "Run load testing",
        description: "Use k6 to simulate traffic and measure response times.",
        assignedTo: "bob",
        dueDate: new Date("2025-09-22T13:15:00Z"),
        priority: "High",
        status: "To Do",
        isArchived: false,
    }),
    new Task({
        id: 22,
        title: "Implement role-based access control",
        description: "Restrict sensitive features to admins only.",
        assignedTo: "carol",
        dueDate: new Date("2025-09-24T16:30:00Z"),
        priority: "High",
        status: "In-progress",
        isArchived: false,
    }),
    new Task({
        id: 23,
        title: "Add multi-language support",
        description: "Localize the UI to support English and Spanish.",
        assignedTo: "dave",
        dueDate: new Date("2025-09-26T09:30:00Z"),
        priority: "Medium",
        status: "To Do",
        isArchived: false,
    }),
    new Task({
        id: 24,
        title: "Audit third-party dependencies",
        description: "Check npm packages for vulnerabilities.",
        assignedTo: "eve",
        dueDate: new Date("2025-09-28T15:00:00Z"),
        priority: "High",
        status: "Done",
        isArchived: false,
    }),
    new Task({
        id: 25,
        title: "Improve mobile responsiveness",
        description: "Fix layout issues on small screen devices.",
        assignedTo: "frank",
        dueDate: new Date("2025-09-30T11:00:00Z"),
        priority: "Medium",
        status: "In-progress",
        isArchived: false,
    }),
    new Task({
        id: 26,
        title: "Setup backup system",
        description: "Automate daily backups for production database.",
        assignedTo: "alice",
        dueDate: new Date("2025-10-02T14:45:00Z"),
        priority: "High",
        status: "To Do",
        isArchived: false,
    }),
    new Task({
        id: 27,
        title: "Review pull requests",
        description: "Check open PRs for code quality and merge conflicts.",
        assignedTo: "bob",
        dueDate: new Date("2025-10-04T12:15:00Z"),
        priority: "Low",
        status: "Done",
        isArchived: true,
    }),
];
