import Task from "./Task";

export const MOCK_TASKS = [
    new Task({
        id: 1,
        title: "Design login page",
        description: "Create a responsive login page for the app.",
        assignedTo: "alice",
        dueDate: new Date("2025-08-15T10:00:00Z"),
        priority: "High",
        status: "In-progress",
        isArchived: false,
    }),
    new Task({
        id: 2,
        title: "Fix navigation bug",
        description: "Resolve the issue with navbar collapsing on mobile.",
        assignedTo: "bob",
        dueDate: new Date("2025-08-10T12:00:00Z"),
        priority: "Medium",
        status: "To Do",
        isArchived: false,
    }),
    new Task({
        id: 3,
        title: "Set up CI pipeline",
        description: "Integrate GitHub Actions for continuous integration.",
        assignedTo: "carol",
        dueDate: new Date("2025-08-20T08:30:00Z"),
        priority: "High",
        status: "In-progress",
        isArchived: false,
    }),
    new Task({
        id: 4,
        title: "Write unit tests",
        description: "Cover components with Jest unit tests.",
        assignedTo: "dave",
        dueDate: new Date("2025-08-18T15:00:00Z"),
        priority: "Low",
        status: "To Do",
        isArchived: false,
    }),
    new Task({
        id: 5,
        title: "Deploy to staging",
        description: "Push the latest build to the staging environment.",
        assignedTo: "eve",
        dueDate: new Date("2025-08-12T13:45:00Z"),
        priority: "Medium",
        status: "Done",
        isArchived: false,
    }),
    new Task({
        id: 6,
        title: "Archive old logs",
        description: "Move outdated log files to the archive bucket.",
        assignedTo: "frank",
        dueDate: new Date("2025-08-08T09:00:00Z"),
        priority: "Low",
        status: "Done",
        isArchived: true,
    }),
    new Task({
        id: 7,
        title: "This is a dummy task",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        assignedTo: "Anurag",
        dueDate: new Date("2025-08-08T09:00:00Z"),
        priority: "High",
        status: "Done",
        isArchived: true,
    }),
];
