import { Task } from "./Task";

export const MOCK_TASKS = [
    new Task({
        id: 1,
        title: "Design login page",
        description: "Create a responsive login page for the app.",
        assignedTo: "alice",
        dueDate: new Date("2025-08-15T10:00:00Z"),
        priority: "high",
        status: "in-progress",
        isArchived: false,
    }),
    new Task({
        id: 2,
        title: "Fix navigation bug",
        description: "Resolve the issue with navbar collapsing on mobile.",
        assignedTo: "bob",
        dueDate: new Date("2025-08-10T12:00:00Z"),
        priority: "medium",
        status: "todo",
        isArchived: false,
    }),
    new Task({
        id: 3,
        title: "Set up CI pipeline",
        description: "Integrate GitHub Actions for continuous integration.",
        assignedTo: "carol",
        dueDate: new Date("2025-08-20T08:30:00Z"),
        priority: "high",
        status: "in-progress",
        isArchived: false,
    }),
    new Task({
        id: 4,
        title: "Write unit tests",
        description: "Cover components with Jest unit tests.",
        assignedTo: "dave",
        dueDate: new Date("2025-08-18T15:00:00Z"),
        priority: "low",
        status: "todo",
        isArchived: false,
    }),
    new Task({
        id: 5,
        title: "Deploy to staging",
        description: "Push the latest build to the staging environment.",
        assignedTo: "eve",
        dueDate: new Date("2025-08-12T13:45:00Z"),
        priority: "medium",
        status: "done",
        isArchived: false,
    }),
    new Task({
        id: 6,
        title: "Archive old logs",
        description: "Move outdated log files to the archive bucket.",
        assignedTo: "frank",
        dueDate: new Date("2025-08-08T09:00:00Z"),
        priority: "low",
        status: "done",
        isArchived: true,
    }),
];
